version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: ls /usr/local/lib/python3.8/dist-packages
          name: Found PyInstaller
      - run:
          command: /usr/local/lib/python3.8/dist-packages/PyInstaller -F ./ScriptBlockPlusCommandSpawner.py
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
